### ISSUE TITLE
No meta_models folder inside prompts

### ISSUE THREAD

**Issue by rafiktelli** [wbsg-uni-mannheim/ExtractGPT#2]
Hello again sir, 
I am encountering this error due to the absence of the json files of meta_models which are ignored by in git. 
Traceback (most recent call last):
  File "/home/user/projects/ExtractGPT/prompts/2_zero_shot_schema/zero_shot_schema_description.py", line 222, in <module>
    main()
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/projects/ExtractGPT/prompts/2_zero_shot_schema/zero_shot_schema_description.py", line 117, in main
    with open('prompts/meta_models/models_by_{}_{}.json'.format(task_dict['task_name'], 'default_gpt3_5', task_dict['dataset_name']), 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'prompts/meta_models/models_by_chatgpt_only_description_compact_default_gpt3_5.json'

**Comment by abrinkmann** [comment]
Please check if the latest commit fixed the problem for you.
